mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

from django.conf.urls.static import static
from django.contrib.auth import views as  auth_views

from django.conf import settings
import user,post,project


urlpatterns = [
    path('admin/', admin.site.urls),
    
    url('ckeditor/', include('ckeditor_uploader.urls')),
    path('tinymce/', include('tinymce.urls')),
  
   
    path('',include('user.urls')),
   	path('',include('post.urls')),
   	path('',include('project.urls')),

     path('password-reset/', 
        auth_views.PasswordResetView.as_view(template_name='templates/password-reset.html'),
         name='password-reset'),
    path('password-reset/done/', 
        auth_views.PasswordResetDoneView.as_view(template_name='templates/password-reset-done.html'),
         name='password-reset-done'),

    path('password-reset-confirm/<uidb64>/<token>',
        auth_views.PasswordResetConfirmView.as_view(template_name='templates/password_reset_confirm.html'),
         name='password_reset_confirm'),
   
   

   
   

]

urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

post/urls.py
''' POST URLS '''

from django.urls import path
from . import views

app_name = 'post'

urlpatterns = [
  
    path('posts/',  views.postlist.as_view() , name="Posts"),
    path('postslist/', views.postlistview, name="postslist"),
    path('posts/<slug:pk>/', views.postdetail, name="Post_Details"),
    path('folders/<slug:pk>/', views.folder, name="Folder"),
    
    path('createpost/', views.createpost.as_view(), name="Create_Post"),
    path('postdetail/<slug:slug>/', views.postdetailview.as_view(), name= "postdetail"),
    path('updatepost/<slug:slug>/', views.updatepostclass.as_view(), name= "updatepost"),
    #path('<slug:ppk>/<slug:pk>/updatepost/', views.updatepost, name="Update_Post"),
    path('<slug:pk>/updatepost/', views.updatepost, name="Update_Post"),
    
    path('<slug:ppk>/<slug:pk>/deletepost/', views.deletepost, name="Delete_Post"),
    
    path('validate-tag/' , views.validatetag, name='validate-tag'),
    path('tag_complete', views.tagcomplete , name='tag_complete'),

    path('tagserach/<pk>/', views.tagserach, name= 'searchtag'),
    path('tagserachs/<pk>/' , views.posttagdetail.as_view(), name='tagserachs'),
]

user/urls.py
from django.urls import path
from django.contrib.auth import views as  auth_views


#from . import views
from . import views 

app_name = 'user'

urlpatterns = [
    path('', views.home),
    path('signup/', views.signup),
    path('sign/',views.sign),
    path('home/' , views.home, name='home'),
    path('p/<slug:pk>/',views.profile, name='profile'),
   	path('p/<slug:pk>/<is_page>/update-profile/',views.updateprofile, name='updateprofile'),
    path('validate-username/', views.validate_username,name='validate-username'),

    path('createpage/', views.createpage.as_view(), name="createpage"),

    path('follow/<pk>/<is_page>/', views.follow, name='follow'),
    path('follows/<pk>/', views.follows, name='follows'),
    path('for_followers/', views.for_followers , name='for_followers'),

    path('ownlogin/', views.ownlogin, name='ownlogin'),
    path('login/', auth_views.LoginView.as_view(template_name='user/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='user/sign.html'), name='logout'),
   
   

    	





   
   


]

user/models.py
''' USER MODEL '''

from django.db import models
from django.utils.text import slugify as inbuilt_slugify

from django.contrib.auth.models import User as auth_user
from django.utils import timezone
from slugify import UniqueSlugify,Slugify
from PIL import Image

from django.urls import reverse
#from django.shortcuts import redirect

from django.contrib.contenttypes.fields import GenericForeignKey,GenericRelation
from django.contrib.contenttypes.models import ContentType

''' some logic '''
#custom_slugify = UniqueSlugify()

custom_slugify=Slugify()



# Create your models here.

''' College list '''
class College(models.Model):
  name    =models.CharField(max_length=200)
  district=models.CharField(max_length=100)
  state   =models.CharField(max_length=100)
  
  def __str__(self):
    return self.name

''' User MOdel '''
class User(auth_user):
  
  TYPE =[
    ('STUDENT','student'),
    ('EDUCATOR','Proffesor/Teacher/Educator')
    ]
  
  college     = models.ForeignKey(College,on_delete=models.SET_NULL,null=True)
    
  dob         = models.DateField(blank=False)
  user_mode   = models.CharField(max_length=10, choices=TYPE, default ='STUDENT')
  date_created  = models.DateTimeField(auto_now_add=True, blank=False)
  #previous_login = models.DateTimeField(default=timezone.now)
  profile      = GenericRelation('Profile', related_query_name='users')


  
  
      
  def full_name(self):
    return self.first_name+' ' +self.last_name
  
  def profile_name(self):
    return self.username
  
  def is_page(self):
    
    return False
  
  def __str__(self):
    return self.first_name+' ' +self.last_name


  


class Page(models.Model):
  name        =models.CharField(max_length=600)
  members     =models.ManyToManyField( User)
  college     =models.ForeignKey(College,on_delete=models.CASCADE, blank= True, default=1)
  date_created=models.DateTimeField(auto_now_add=True, blank=False) 
  profile      = GenericRelation('Profile', related_query_name='pages') 

  
  def full_name(self):

      return self.name

    
  def profile_name(self):
    return self.name
  
  def is_page(self):
    return True
  
  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return reverse('user:home' ,kwargs={})
 


class Profile(models.Model):
 

    limit = models.Q(model='user') | models.Q(model ='page')

    content_type = models.ForeignKey(
        ContentType,
       on_delete=models.CASCADE,
        limit_choices_to=limit,
        
        blank=False,
    )

    object_id = models.PositiveIntegerField(
        blank=True,
        null =False
    )

    content_object = GenericForeignKey('content_type', 'object_id')
    
    slug =models.SlugField(blank=True,unique=True)
    img = models.ImageField( default='profile_pics/default.png',upload_to='profile_pics')
    description = models.TextField(default='hai',blank=True)


    @property
    def college(self):
      return str(self.content_object.college)
 
    
    def __str__(self):
        return self.content_object.full_name()
       
    def save(self, *args, **kwargs):

       self.slug=custom_slugify(self.content_object.profile_name(), allow_unicode=True)
       super().save(*args, **kwargs)
       
       img = Image.open(self.img.path)
       if img.height > 300 or img.width > 300:
        output_size = (300, 300)
        img.thumbnail(output_size)
        img.save(self.img.path)
    
    def college(self):
    
      return str(self.content_object.college)
 



class Follower(models.Model):
  from_profile =models.ForeignKey(Profile,on_delete=models.CASCADE,
   related_name='followers')
  
  to_profile   =models.ForeignKey(Profile,on_delete=models.CASCADE, 
    related_name='following')
  
  date_created =models.DateTimeField(auto_now_add=True) 
  
  def __str__(self):
    return str(self.from_profile) +' follow '+ str(self.to_profile)
    
  
    


    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    

post/forms.py
''' POST FORMS'''

from .models import Post,Tag
from django import forms
from tinymce.widgets import TinyMCE
from ckeditor.widgets import CKEditorWidget
from ckeditor_uploader.widgets import CKEditorUploadingWidget


''' USER FORMS '''


from .models import *



class PostCreationForm(forms.ModelForm):
  tt = forms.CharField(widget=forms.TextInput())
  #body = forms.CharField(widget=CKEditorWidget())
   
  #body = forms.CharField(widget=TinyMCE(attrs={'cols': 30, 'rows': 30}))

  #body = forms.CharField(widget=TinyMCE(attrs={'cols': 80, 'rows': 30}))
    
  

  class Meta:
    model = Post
    fields = (
    	'author',
    	'title',
    	'description',
    	'body',
        'tt',
    	'comments',
    	'visibility',
    	'college_visibility'
    	)


class PostUpdationForm(forms.ModelForm):
  
  def hai(self):
    print(self.man)
    return self.man


  tt = forms.CharField(widget=forms.TextInput())
  #body = forms.CharField(widget=TinyMCE(attrs={'cols': 80, 'rows': 30}))
    
  

  class Meta:
    model = Post
    fields = (
        'title',
        'description',
        'body',
        'tt',
        'comments',
        'visibility',
        'college_visibility'
        )


  def __init__(self,*args,**kwargs):
    #self.man = kwargs.pop('man')
    #self.man = 'Hai'
    
    super(PostUpdationForm,self).__init__(*args,**kwargs)
    tagstring=''
    for tags in self.instance.tags.all():
        tagstring+=tags.tag_name+'--'

    self.fields['tt'].widget.attrs['value']=tagstring
    #print('hello :',self.instance.tags.all())

  '''

  form.  


  '''

post/views.py
''' Post VIEWS '''

from django.shortcuts import render
from django.http import HttpResponse,JsonResponse

from django.utils import timezone
from datetime import timedelta
from django.views.generic import CreateView,ListView,DetailView,UpdateView
from django.db.models import Q
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from django_filters.views import FilterView

from .models import *
from .forms import *
from .filters import *
from user.models import *

# Create your views here.

def posts(request):
  return HttpResponse('<h1>Posts List</h1>')



def postdetail(request,pk):
  


  def get_ip(request):
    address = request.META.get('HTTP_X_FORWARDED_FOR')

    if address:
      ip = address.split(',')[-1].strip()
    else:
      ip=request.META.get('REMOTE_ADDR')
    return ip

  post=Post.objects.get(slug=pk)
  #print(request.session)
  key=post.slug
  session = request.session.get(key)
  if request.user.is_authenticated and get_ip(request) and not session:
    #if timezone.now()-request.user.user.previous_login>timedelta(minutes=1):
      #print('kljdsf;s')
      post.views+=1
      post.save()
      request.session[key]=True
  


  context={
  'post':post
  }
  #key=post.slug
  #print(request.user.last_login)
  #print(timezone.now())
  #diffrence = (timedelta(minutes=1))
  #print(diffrence)
  #print(timezone.now()-request.user.last_login>diffrence)
  #print(key)
  #print(request.session.get(key))

  #print(request.session._session_cache)



  return render(request,'post/postdetail.html',context)

 

class postdetailview(DetailView):
  model = Post
  template_name= 'post/postdetail.html'
  context_object_name='post'


def folder(request,pk):
  p=PostDirectory.objects.get(slug=pk)
  return HttpResponse(f'<h1>Folders {p.owner}</h1><p>Authored by {p.name}</p>')
  
class createpost(CreateView):
  model = Post
  form_class = PostCreationForm
  template_name = 'post/createpost.html'

  def form_valid(self, form):
      data = form.cleaned_data['tt']
      print(data)
      form.save()
      print(len(data))
  
      for i in data.split('--')[:-1]:
        try:
          #print(i,type(i))
          tag = Tag.objects.get(tag_name__iexact=i)
          #print(tag,tag.tag_name,tag.id)
          print('existing tag')
        except:
          tag = Tag.objects.create(tag_name=i)
          tag.save()
          print('non existing tag')
        form.instance.tags.add(tag)
      return super().form_valid(form)


def postlistview(request):
  context ={}
  college = request.user.user.college
  queryset=Post.objects.filter(Q(
        author__users__college__name = college)|Q(
      visibility='PUBLIC')|Q(author__pages__college__name=college))
      
  filterd_posts = PostFilter(
    request.GET,
       queryset = Post.objects.filter(Q(
        author__users__college__name = college)|Q(
      visibility='PUBLIC')|Q(author__pages__college__name=college)),
      user=request.user )
  #print(queryset)
  paginated_filterd_posts = Paginator(filterd_posts.qs,2)
  page_number = request.GET.get('page')
  posts_per_page = paginated_filterd_posts.get_page(page_number)


  context['posts_per_page'] = posts_per_page
  context['filterd_posts'] = filterd_posts
  #print(context['filterd_posts'].__dict__)
 
    
  return render(request,'post/postview.html',context=context)


class postlist(ListView):
  model = Post
  template_name = 'post/posts.html'
  #context_object_name = 'posts'
  paginate_by = 10
  ordering =[ '-date_created']
  
  def get_context_data(self,**kwargs):
    context = super().get_context_data(**kwargs)
    #print(self.request.user.user.college)
    #posts = Post.objects.all()
    college = self.request.user.user.college
    
    context['filter']= PostFilter(self.request.GET, 
      queryset=self.get_queryset().filter(Q(
        author__users__college__name = college)|Q(
        visibility='PUBLIC')|Q(author__pages__college__name=college)),
      user=self.request.user )

    paginated_filterd_posts = Paginator(context['filter'].qs,self.paginate_by)
    page_number = self.request.GET.get('page')
    posts_per_page = paginated_filterd_posts.get_page(page_number)
    context['posts_per_page'] = posts_per_page
  
    return context
  

def updatepost(request,pk):
  #p=Profile.objects.get(slug=pk)
  post=Post.objects.get(slug=pk)
  return HttpResponse(
    f'<h1>Update post </h1><h6>by  { post.author} </h6><p>{post.title}</p>')


class updatepostclass(UpdateView):
  model = Post
  form_class = PostUpdationForm
  template_name = 'post/createpost.html'

  def form_valid(self, form):
      data = form.cleaned_data['tt']
      print(data)
      form.save()
      print(len(data))
      print(form.instance.tags.clear())
  
      for i in data.split('--')[:-1]:
        try:
          #print(i,type(i))
          tag = Tag.objects.get(tag_name__iexact=i)
          #print(tag,tag.tag_name,tag.id)
          print('existing tag')
        except:
          tag = Tag.objects.create(tag_name=i)
          tag.save()
          print('non existing tag')
        form.instance.tags.add(tag)
      return super().form_valid(form)


  




   
def deletepost(request,ppk,pk):
  p=Profile.objects.get(slug=pk)
  post=Post.objects.get(slug=ppk)
  return HttpResponse(
    f'<h1>Delete post </h1><h6>by {p}</h6><p>{post.title}</p>')

''' This is  For Uservalidate in page members'''
def validatetag(request):
  value=request.GET.get('value',None)
  tag=Tag.objects.get(tag_name__iexact=value)
  print(tag)
  print(tag.id)
  return JsonResponse(tag,safe=False)

''' Tag auto complete in Post creation '''
def tagcomplete(request):
  if 'term' in request.GET:
    qs = Tag.objects.filter(tag_name__icontains=request.GET.get('term'))[:10]
    tags = []
    for tag in qs:
      tags.append(tag.tag_name)
      print(tag.tag_name)
    return JsonResponse(tags,safe=False)




def tagserach(request,pk):
  tag = Tag.objects.get(tag_name= pk)
  post= tag.post_set.all()
  context ={
  'post':post
  }
  print('Function Based view')
  return render(request,'post/tagsearch.html',context)

class posttagdetail(ListView):
  model = Post
  template_name = 'post/posts.html'
  #context_object_name = 'posts'
  #ordering =[ '-date_created']
  
  def get_context_data(self,**kwargs):
    context = super().get_context_data(**kwargs)
    context['filter']= PostTagFilter(self.request.GET, 
      queryset=self.get_queryset().filter(tags=self.kwargs['pk']))
    print('class based view')
    return context
 

post/templates/post/createpost.html
{% load bootstrap %}

<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>



<script src="//cdn.tinymce.com/4/tinymce.min.js"></script>


<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>


<script>

  tinymce.init({selector:'.tinymce',
      height : 500,
      max_height: 500,
      min_height: 500,
      
    
     
      
  
      plugins: ' preview paste importcss searchreplace autolink autosave save directionality  visualblocks visualchars fullscreen image link  codesample table charmap hr pagebreak nonbreaking  toc advlist lists wordcount imagetools  noneditable  charmap anchor',
        
      plugin_preview_width : "400", //This do the trick
      plugin_preview_height : "600",

    
      toolbar: 'undo redo | bold italic underline strikethrough | fontselect fontsizeselect formatselect | backcolor alignleft aligncenter alignright alignjustify | superscript subscript  | Blocks | outdent indent |  numlist bullist | forecolor backcolor table hr  removeformat | charmap | fullscreen  preview  |  image  link  anchor codesample |',


      
      codesample_dialog_height: 500,

      toolbar_sticky: true,
      menubar : false,

      
      statusbar: true,
  
      branding : false,
  
  });

</script>


<script type="text/javascript">
	$(function(){
    //alert($("#id_tt").val());
   function addbox(ss){
        prev=0
        for(i=0;i<ss.length-1;i++){
          //console.log(ss[i]);
          //console.log(ss.slice(1,10));
          if (ss[i]=='-' && ss[i+1]=='-'){
            //console.log(ss.slice(prev,i))
            tag = ss.slice(prev,i);
            console.log(tag);
            console.log(i);
            prev  = i+2;
            
            var html = '<pre class="pre-names btn btn-primary m-1">'+tag+'</pre>';
            var remove = '<button class="remove">Delete</button>'
            $( "#names" ).append('<div class="rmv">'+html+remove+'</div>');

            

            }
           
          }
        
      }   
    var text = $('#id_tt').val();
    addbox(text);
        

    $( "#tags" ).autocomplete({
      source: "{% url 'post:tag_complete' %}",
      });
     
    //for disavleig the button 
    if ($('#names .rmv').length <= 5){
      $('#add').prop('disabled',false);
    }
    //console.log('Length before '+ $('#names .rmv').length);


    //for adding
    $( "#add" ).click( function(){
      if ($('#names .rmv').length <= 5){
        $('#add').prop('disabled',false);
      }



    	var value = $( "#tags" ).val();
    	var html = '<pre class="pre-names btn btn-primary m-1">'+value+'</pre>';
        var remove = '<button class="remove">Delete</button>'
    	$( "#names" ).append('<div class="rmv">'+html+remove+'</div>');

    	var previous = $("#id_tt").val();
    	console.log('Previous :' + previous);
    	$("#id_tt").val(previous +value+'--');
    	//console.log('Current : ' +  $("#id_tt").val());
      //console.log('length of all tags :'+$("#names .rmv").length);
      //console.log('Length after adding '+ $('#names .rmv').length);

      //for disabling button
      if ($("#id_tt").val().split('--').length >= 6){
        $('#add').prop('disabled',true);
        
        };


	    });


    //for removing
    $(" #names ").on('click' ,'.remove', function() {
        var value_to_remove=$(this).siblings().html();
        //console.log(h);
        $(this).parent().remove();
        //$("#id_members option").remove(":contains('"+h+"')");

        //limiting no of tags
        //if ($('#id_members option').length <= 4){};
        //$('#add').prop('disabled',false);

      
        //for input box
        function removebox(ss,compare){
          prev=0
          for(i=0;i<ss.length-1;i++){
            if (ss[i]=='-' && ss[i+1]=='-'){
              //console.log(ss.slice(prev,i))
              for_compare = ss.slice(prev,i);
              if (for_compare == compare){
                final = ss.slice(0,prev)+ss.slice(i+2,ss.length);
                //console.log(final);
                return final

              }
              prev  =i+2;
            }
          }
        }
        
        present_input_text=$("#id_tt").val();
        finalvalue = removebox(present_input_text,value_to_remove);
        $("#id_tt").val(finalvalue);

        console.log('Length after removing '+ $('#names .rmv').length);

    });

  





   });







</script>

<body class="bg-light">
    
    <span class="nav-below"></span>
  <div class="container p-0">
    <div class="row">
      <div class="col-md-10 bg-white">

        <h1> Create Post </h1>

        <div class="ui-widget">
          <form>
            <label for="tags">Tags: </label>
            <input id="tags">
            <span class="btn btn-primary" id="add">Add a tag</span>
          </form>
        </div>
        <div id="names" class="mt-5">
        </div>

        <form method="Post">
          {% csrf_token %}
          
          {{ form.media }}

          {{ form|bootstrap }}

          {{ form.bodys }}

        <button class="btn btn-primary"> Create Post</button>
        </form>

       

        

      </div>
   
      
    </div>
    </div>












  <script />























<!-- down side code is not necessary -->
<!-- just check and remove afterwods  -->
{% block javascript %}
   	<script type="text/javascript">
   		$("#add").click(function(){
   			var value = $( "#tags" ).val();
    	
    	

   			$.ajax({
   				url: "{% url 'post:validate-tag' %}",
   				data :{
   					'value':value
   				},
   				success : function(msg){
   					alert(msg);

   				}
   			});
   		});
   	</script>


{% endblock %}
  

post/templates/post/postdetail.html
{% load static %}
{% load bootstrap %}
<!DOCTYPE html>
<html>
<head>
	<title>Posts Detail</title>
	<meta name="theme-color" content="blue"/>

    <meta charset="utf-8" >
    <meta name="view-port" content="width=device-width" initial-scale="1.0">
    
    <!-- Css style sheets and bootstrap -->
    <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

    <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

	<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>

	<!-- Own Css and Js -->
	<link rel="stylesheet" type="text/css"
	 href="{% static 'post/posts.css' %}">
</head>

<body class="bg-light">
    
    <span class="nav-below"></span>
	<div class="container p-0">
		<div class="row">
			<div class="col-md-8 bg-white">
				
					<article class="media content-section-main ">
						<div class="media-body border p-3">
						
							<h4 class="article-title-border pb-2">
								<a  class="article-title ">
								{{ post.title }}
								</a>
								<i class="fa float-right fa-bookmark"></i>
							</h4>
						
							
						
							<div class="article-metadata pb-2">
								<div>
									<img src="{{ post.author.img.url }}" class="rounded-circle profile-small-image">
									<span class="search-sort__sort">
										<a href=""> {{ post.author }}</a>
										<a href="#"><small> {{ post.author.profile_name }}</small></a>
									</span>
									
									<p class="text-muted float-right"> 
									{{  post.date_created }}</p>
								</div>
								<p><i class="fa fa-eye"></i> {{post.views }} views 
									<i class="fa fa-sign-language"></i> {{ post.likes }} appreciations
								</p>
								<p> {{ post.author.college }} </p>
								<div class="article-tags">
									{% for tag in post.tags.all %}
									<a href="{% url 'post:searchtag' tag.tag_name %}" class="tags">{{ tag }} </a>
									{% endfor %}
								</div>
							</div>

							
					

							<div class="article-content text-muted">
								<p> {{ post.description }} </p>
								
							</div>
						
							<div>
								{{ post.body|safe}}
							</div>
						
						</div>
						
					</article>
				
			
					
					
	

			</div>
			<div class="col-md-4  hide-small">
				<div class="content-section">
					<h3 class="text-center">Shortcuts</h3>
					
					<ul>
						
						<a href="profile.html" class="list-group-item  float-center btn shortcuts dropdown-item text-center">Go to your Profile</a>
						<li class="list-group-item btn shortcuts">Your Posts </li>
						
						<li class="list-group-item btn shortcuts">First Page Posts </li>
						<li class="list-group-item btn shortcuts">Second Page Posts </li>
					</ul>
				    		
				</div>
			</div>
			
		</div>
    </div>












	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

	<!-- Latest compiled JavaScript -->
	
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>

	 <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>

	 <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>






</body>
</html>