mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

from django.conf.urls.static import static
from django.contrib.auth import views as  auth_views

from django.conf import settings
import user,post,project


urlpatterns = [
    path('admin/', admin.site.urls),
    
    url('ckeditor/', include('ckeditor_uploader.urls')),
    path('tinymce/', include('tinymce.urls')),
  
   
    path('',include('user.urls')),
   	path('',include('post.urls')),
   	path('',include('project.urls')),

     path('password-reset/', 
        auth_views.PasswordResetView.as_view(template_name='templates/password-reset.html'),
         name='password-reset'),
    path('password-reset/done/', 
        auth_views.PasswordResetDoneView.as_view(template_name='templates/password-reset-done.html'),
         name='password-reset-done'),

    path('password-reset-confirm/<uidb64>/<token>',
        auth_views.PasswordResetConfirmView.as_view(template_name='templates/password_reset_confirm.html'),
         name='password_reset_confirm'),
   
   

   
   

]

urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

post/urls.py
''' POST URLS '''

from django.urls import path
from . import views

app_name = 'post'

urlpatterns = [
  
    path('posts/',  views.postlist.as_view() , name="Posts"),
    path('postslist/', views.postlistview, name="postslist"),
    path('posts/<slug:pk>/', views.postdetail, name="Post_Details"),
    path('folders/<slug:pk>/', views.folder, name="Folder"),
    
    path('createpost/', views.createpost.as_view(), name="Create_Post"),
    path('postdetail/<slug:slug>/', views.postdetailview.as_view(), name= "postdetail"),
    path('updatepost/<slug:slug>/', views.updatepostclass.as_view(), name= "updatepost"),
    #path('<slug:ppk>/<slug:pk>/updatepost/', views.updatepost, name="Update_Post"),
    path('<slug:pk>/updatepost/', views.updatepost, name="Update_Post"),
    
    path('<slug:ppk>/<slug:pk>/deletepost/', views.deletepost, name="Delete_Post"),
    
    path('validate-tag/' , views.validatetag, name='validate-tag'),
    path('tag_complete', views.tagcomplete , name='tag_complete'),

    path('tagserach/<pk>/', views.tagserach, name= 'searchtag'),
    path('tagserachs/<pk>/' , views.posttagdetail.as_view(), name='tagserachs'),
]

user/urls.py
from django.urls import path
from django.contrib.auth import views as  auth_views


#from . import views
from . import views 

app_name = 'user'

urlpatterns = [
    path('', views.home),
    path('signup/', views.signup),
    path('sign/',views.sign),
    path('home/' , views.home, name='home'),
    path('p/<slug:pk>/',views.profile, name='profile'),
   	path('p/<slug:pk>/<is_page>/update-profile/',views.updateprofile, name='updateprofile'),
    path('validate-username/', views.validate_username,name='validate-username'),

    path('createpage/', views.createpage.as_view(), name="createpage"),

    path('follow/<pk>/<is_page>/', views.follow, name='follow'),
    path('follows/<pk>/', views.follows, name='follows'),
    path('for_followers/', views.for_followers , name='for_followers'),

    path('ownlogin/', views.ownlogin, name='ownlogin'),
    path('login/', auth_views.LoginView.as_view(template_name='user/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='user/sign.html'), name='logout'),
   
   

    	





   
   


]

user/models.py
''' USER MODEL '''

from django.db import models
from django.utils.text import slugify as inbuilt_slugify

from django.contrib.auth.models import User as auth_user
from django.utils import timezone
from slugify import UniqueSlugify,Slugify
from PIL import Image

from django.urls import reverse
#from django.shortcuts import redirect

from django.contrib.contenttypes.fields import GenericForeignKey,GenericRelation
from django.contrib.contenttypes.models import ContentType

''' some logic '''
#custom_slugify = UniqueSlugify()

custom_slugify=Slugify()



# Create your models here.

''' College list '''
class College(models.Model):
  name    =models.CharField(max_length=200)
  district=models.CharField(max_length=100)
  state   =models.CharField(max_length=100)
  
  def __str__(self):
    return self.name

''' User MOdel '''
class User(auth_user):
  
  TYPE =[
    ('STUDENT','student'),
    ('EDUCATOR','Proffesor/Teacher/Educator')
    ]
  
  college     = models.ForeignKey(College,on_delete=models.SET_NULL,null=True)
    
  dob         = models.DateField(blank=False)
  user_mode   = models.CharField(max_length=10, choices=TYPE, default ='STUDENT')
  date_created  = models.DateTimeField(auto_now_add=True, blank=False)
  #previous_login = models.DateTimeField(default=timezone.now)
  profile      = GenericRelation('Profile', related_query_name='users')


  
  
      
  def full_name(self):
    return self.first_name+' ' +self.last_name
  
  def profile_name(self):
    return self.username
  
  def is_page(self):
    
    return False
  
  def __str__(self):
    return self.first_name+' ' +self.last_name


  


class Page(models.Model):
  name        =models.CharField(max_length=600)
  members     =models.ManyToManyField( User)
  college     =models.ForeignKey(College,on_delete=models.CASCADE, blank= True, default=1)
  date_created=models.DateTimeField(auto_now_add=True, blank=False) 
  profile      = GenericRelation('Profile', related_query_name='pages') 

  
  def full_name(self):

      return self.name

    
  def profile_name(self):
    return self.name
  
  def is_page(self):
    return True
  
  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return reverse('user:home' ,kwargs={})
 


class Profile(models.Model):
 

    limit = models.Q(model='user') | models.Q(model ='page')

    content_type = models.ForeignKey(
        ContentType,
       on_delete=models.CASCADE,
        limit_choices_to=limit,
        
        blank=False,
    )

    object_id = models.PositiveIntegerField(
        blank=True,
        null =False
    )

    content_object = GenericForeignKey('content_type', 'object_id')
    
    slug =models.SlugField(blank=True,unique=True)
    img = models.ImageField( default='profile_pics/default.png',upload_to='profile_pics')
    description = models.TextField(default='hai',blank=True)


    @property
    def college(self):
      return str(self.content_object.college)
 
    
    def __str__(self):
        return self.content_object.full_name()
       
    def save(self, *args, **kwargs):

       self.slug=custom_slugify(self.content_object.profile_name(), allow_unicode=True)
       super().save(*args, **kwargs)
       
       img = Image.open(self.img.path)
       if img.height > 300 or img.width > 300:
        output_size = (300, 300)
        img.thumbnail(output_size)
        img.save(self.img.path)
    
    def college(self):
    
      return str(self.content_object.college)
 



class Follower(models.Model):
  from_profile =models.ForeignKey(Profile,on_delete=models.CASCADE,
   related_name='followers')
  
  to_profile   =models.ForeignKey(Profile,on_delete=models.CASCADE, 
    related_name='following')
  
  date_created =models.DateTimeField(auto_now_add=True) 
  
  def __str__(self):
    return str(self.from_profile) +' follow '+ str(self.to_profile)
    
  
    


    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    

user/forms.py
''' USER FORMS '''

from django.contrib.auth.forms import UserCreationForm
#from django.contrib.auth.models import User
from django import forms


#from django.contrib.auth.models import User
from django.db import models
from .models import *

#some logic



class UserRegistrationForm(UserCreationForm):

  username = forms.CharField(widget=forms.TextInput(attrs={'id':'username','class':'box-input'}))
  first_name = forms.CharField(widget=forms.TextInput(attrs={'id':'first','class':'box-input'}))
  last_name = forms.CharField(widget=forms.TextInput(attrs={'id':'second','class':'box-input'}))
  email = forms.EmailField(widget=forms.TextInput(attrs={'id':'email','class':'box-input'}))
  #college = forms.TypedChoiceField(choices=CHOICES)
  dob = forms.DateTimeField(widget=forms.TextInput(attrs={'id':'date','class':'box-input','type':'date'}))
  password1 = forms.CharField(widget=forms.TextInput(attrs={'id':'password1','class':'box-input'}))
  password2 = forms.CharField(widget=forms.TextInput(attrs={'id':'password2','class':'box-input'}))
  

  class Meta:
    model = User
   
    fields= (
      'username',
      'first_name',
      'last_name',
      'email',
      'user_mode',
      'college',
      'dob',
      'password1',
      'password2',
     
       )

class ProfileUpdateForm(forms.ModelForm):
  description = forms.CharField(widget=forms.TextInput())
  

  class Meta:
    model = Profile
    fields = ['img','description']


class UserUpdateForm(forms.ModelForm):
  class Meta:
    model = User
    fields = ['email']

class PageUpdateForm(forms.ModelForm):
  #members = forms.ModelMultipleChoiceField(widget=forms.SelectMultiple(),queryset=queryset)
  #members.widget.attrs.update({'style':'display:none;'})
  #members = forms.CharField(widget=forms.TextInput(attrs={'style':'display:none;','class':'box-input'}))
  

  class Meta:
    model = Page
    fields = ['name','members']

class LoginForm(forms.ModelForm):
  username_email = forms.CharField(widget=forms.TextInput(attrs={'id':'username','class':'box-input'}))
  
  password = forms.CharField()
    
  #user = forms.CharField(widget=forms.TextInput(attrs={'id':'username','class':'box-input'}))
  #password = forms.CharField(widget=forms.TextInput(attrs={'id':'username','class':'box-input'}))
  
  class Meta:
    model=User
    fields = ['username_email','password']

user/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse,JsonResponse
from django.db.models import Q

# Create your views here.
from django.views.decorators.csrf import csrf_exempt
from django.contrib import auth
from django.contrib import messages
from .models import *
from .forms import *

from django.views.generic import CreateView,ListView,DetailView

from django.contrib.auth.forms import UserCreationForm

def home(request):
	return render(request,'user/base.html')


def sign(request):
	if request.method=='POST':
		form = UserRegistrationForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('user:home')
	else:
		form=UserRegistrationForm()
	return render(request,'user/sign.html',{'form':form})

def signup(request):
	if request.method=='POST':
		form = UserRegistrationForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('user:login')
	else:
		form=UserRegistrationForm()
	return render(request,'user/signup.html',{'form':form})

def ownlogin(request):
	form = LoginForm()
	if request.method == 'POST':
		name = request.POST['username_email']
		password = request.POST['password']
		#password = 'pbkdf2_sha256$216000$g9NLoDQQD6Vs$Fk5KOgSCAeJ82N51xyTVIQtCdhtG9v8I5ezil9nXqo8='
		try :
			user = auth.authenticate(username=User.objects.get(email=name).username, password= password)
		except:
			user = auth.authenticate(username=name, password=password)
		if user is not None:
			auth.login(request,user)
			return redirect('user:home')
		else:
			messages.error(request, 'Usernae or password is Wrong?')
		

	return render(request,'user/login.html', context={'form':form})


def profile(request,pk):
	profile=Profile.objects.get(slug=pk)
	if profile.content_object.is_page():
		members = profile.content_object.members.all()
		context = {'profile':profile,'members': members}
	else:
		context = {'profile':profile}

	return render(request,'user/profile.html', context)


class createpage(CreateView):
	model = Page
	fields = ['name']
	template_name = 'user/createpage.html'

	def form_valid(self, form):
		form.save()
		form.instance.members.add(self.request.user.user)
		#form.instance.college = self.request.user.user.college
		return super().form_valid(form)






def updateprofile(request,pk,is_page):
	profile = Profile.objects.get(slug=pk)
	if request.method == 'POST':
		profile_form =ProfileUpdateForm(request.POST ,request.FILES,
			instance=profile)
		if is_page=='True':
			print('page Update Post')
			unique_form = PageUpdateForm(request.POST,
				instance=Page.objects.get(name=profile.content_object))
		else:
			print('User update Post')
			#print(type(User.objects.get(username=profile.content_object.username)))
			unique_form = UserUpdateForm(request.POST,
				instance = User.objects.get(username=profile.content_object.username))
		
		 
		if profile_form.is_valid() and unique_form.is_valid():
			
			profile_form.save()
			unique_form.save()
			print('update view',profile.slug)
			return redirect('user:profile', pk=profile.slug)
		
	else:
		profile_form = ProfileUpdateForm(instance=profile)
		if is_page=='True':
			unique_form = PageUpdateForm(instance=Page.objects.get(name=profile.content_object))
		else:
			unique_form = UserUpdateForm(instance=User.objects.get(username=profile.content_object.username))

		#form= UserUpdateForm(instance=Profile.objects.get(slug=pk))
	
	context ={'profile_form':profile_form,'unique_form':unique_form}

	return render(request,'user/updateprofile.html',context)



def validate_username(request):
	username=request.GET.get('username',None)
	data = {
		'is_taken': User.objects.filter(username__iexact=username).exists()
	}
	
	if data['is_taken']:
		msg='User with that username already exists'
	elif ' ' in username :
		msg='Invalid Username'
	else:
		msg='Username is available'
		
	return JsonResponse(msg,safe=False)

@csrf_exempt
def follow(request,pk,is_page):
	print(pk)

	from_user=Profile.objects.filter(users__username=request.user).first()
	
	if is_page=='True':
		to_user= Profile.objects.filter(slug=pk).first()
	else:
		to_user =Profile.objects.filter(slug=pk).first() 
	
	#print(from_user,to_user,is_page)
	if Follower.objects.filter(from_profile=from_user,to_profile=to_user).exists():
		Follower.objects.filter(from_profile=from_user,to_profile=to_user).delete()
		#print('Deleted')
		msg = 'Deleted'

		
	else:
		Follower.objects.create(from_profile=from_user,to_profile=to_user)
		#print('Created')
		msg = 'Created'
	print(msg)
	return JsonResponse(msg,safe=False)


@csrf_exempt
def follows(request,pk):
	print(pk)
	#print('hello')
	to_user= Profile.objects.filter(slug=pk).first()
	
	from_user=Profile.objects.filter(users__username=request.user).first()
	print(from_user)
	if request.method == 'POST':
		if Follower.objects.filter(from_profile=from_user,to_profile=to_user).exists():
			Follower.objects.filter(from_profile=from_user,to_profile=to_user).delete()
			#print('Deleted')
			msg = 'Deleted'

		
		else:
			Follower.objects.create(from_profile=from_user,to_profile=to_user)
		#print('Created')
			msg = 'Created'
	print(msg)
	return JsonResponse(msg,safe=False)


	'''
	name = request.POST['user']
	#page = request.POST['page']
	from_user=Profile.objects.filter(id=int(name))
	to_user =Profile.objects.filter(id=int(page))
	print(from_user,to_user)
	if Follower.objects.filter(from_profile=from_user,to_profile=to_user).exists():
		Follower.objects.filter(from_profile=from_user,to_profile=to_user).delete()
		print('Deleted')
		msg = 'Follow'
	'''





def for_followers(request):
	#print('yes got it')
	pp = Profile.objects.get(users__username=request.user)
	#ff = list(Follower.objects.filter(from_profile=pp).values())
	fo = Follower.objects.filter(to_profile=pp)
	ff = list(pp.followers.all().values())
	print(request.user)
	print(pp)
	print(ff)
	profile_list=[]
	for i in range(len(ff)):
		profile = Profile.objects.get(id = ff[i]['to_profile_id'])
		profile_values =  {
						'name': str(profile), 
						'img': profile.img.url,
						'slug':profile.slug
		 				}
		profile_list.append(profile_values)
	print(profile_list)


	return JsonResponse(profile_list,safe=False)

		
		

	

	
	

user/templates/user/profile.html
{% extends 'base.html' %}
{% load static %}
{%  block css %}
	<link rel="stylesheet" href="{% static 'user/profile.css' %}" type="text/css" />

{%  endblock %}

{% block content %}
<span class="nav-below"></span>
<div class="container bg-white">
		<div class="row">
			<div class="col-md-8">

				<div class="profile-card  my-2 pb-2 shadow  ">
					
					<div class="pl-4 text-center ">
						{{ profile.img.url }}
						<img src="{{ profile.img.url }}" 
						class="rounded-circle ml-2 ml-lg-4 mt-4 p-1"
						style="width: 200px; height: 200px;">
						<form class="mt-2 ml-lg-4"  id="follow">
							<a class="btn btn-primary px-5  text-white">
   			
							Follow</a>
						</form>
						<form id="follow2">
						 	
							<button   class="btn btn-primary">
							Followers </button>
						</form>
						
					</div>
					<div class=" mt-1 p-1"> 
						<div class="divider border-0 ">
							<h3> {{ profile.content_object.full_name }} </h3>
							<a href="{% url 'user:updateprofile' profile.slug profile.content_object.is_page %}" class="text-secondary">Edit <i class="fa fa-edit"></i></a>
						</div>
					
						<p><span>@</span>{{ profile.content_object.profile_name }} 
							</p>
						<p>{{ profile.content_object.college }}</p>

						{% if profile.content_object.is_page %}	
							<h4>Members</h4>
							{%  for members in members %}
								<p>{{ members }}</p>
							
							{% endfor %}
						{% else %}
						<p> User Mode: {{ profile.content_object.user_mode }} </p>      


						<p>Email:<span class=""></span> {{ profile.content_object.email }} </p>

						{% endif %}
						<p> {{ profile.description}} </p>
						
						
					</div>

					<div class="mt-2 text-center">
						<div class="d-inline-block">
							<p class="text-center m-0 ">1000</p>
							
							
							<button type="button" class="btn btn-secondary border-0 m-0 pt-0 " data-toggle="modal" 
							data-target="#exampleModalCenter" id="for_followers">
								Followers
	 
							</button>


						
						</div>
						<div class="d-inline-block">
							<p class="text-center m-0  ">1000</p>
							
							<button type="button" class="btn btn-outline-secondary border-0 m-0 pt-0 " data-toggle="modal" data-target="#exampleModalCenter2">
								Following
	 
							</button>
						
						
						</div>
						

					</div>
					<div class="dropdown d-inline-block d-sm-block d-none  d-md-none float-right py-1 my-4 text-center">
							<button class="btn btn-primaray dropdown-toggle bg-success text-white" type="button" id="dropdown-menu-button" data-toggle="dropdown" aria-expanded="false" aria-haspopup>
							  Shortcuts
							</button>
							<div class="dropdown-menu " aria-labelledby="dropdown-menu-button">    
								<a href="posts.html" class="dropdown-item list-group-item shortcuts">Go to your Posts</a>
						
								<a href="d" class="dropdown-item list-group-item shortcuts">Create Project</a>
								<a href="dd" class="dropdown-item shortcuts">Create Post</a>
								<a class="list-group-item dropdown-item shortcuts" >Create Post</a>
								<a class="list-group-item btn shortcuts">Create Project</a>
								
							</div>
					
					</div>

					
							
				</div>

				

			    <div class=" p-3 shadow rounded my-4 ">
					<div class="divider bg-light my-3 p-2">
						<h2  >Posts</h2>
						<a href="folder.html" class="align-center">see more</a>
					</div>
					<div>
						<h4>My first post</h4>
						<p>Goood to see you all of the </p>
					</div>
					<div>
						<h4>My SEcond post</h4>
						<p>My name is aAja kumare what else you can do</p>
					</div>
					<article class="media border-0 content-section-main ">
						<div class="media-body  p-0">
						
							<h4 class="article-title-border pb-2">
								<a href="#" class="article-title ">
									Python Part 4 , Go and grab the opurtunity
								</a>
								<i class="fa float-right text-white fa-bookmark"></i>
							</h4>
							<i class="fa float-right text-white fa-bookmark"></i>
							
						
							<div class="article-metadata border-bottom pb-2">
								<div>
									
									
									<p class="text-muted float-right">  3 June,2020</p>
								</div>
								<p><i class="fa fa-eye"></i> 20 views 
									<i class="fa fa-sign-language"></i> 50 appreciations
								</p>
								<div class="article-tags">
									<a class="tags">Python</a>
									<a class="tags">Django</a>
								    <a class="tags">Html</a>
									<a href="" class="tags">Wow </a>
								</div>
							</div>

							
					

							<div class="article-content text-muted">
								<p>My name is Ajay Kumar and I wnat to kanow how are the things goint gin th ps f </p>
								
							</div>
							<button type="submit" class="btn btn-outline-info">See the full Post</button>
					
						
						</div>
						
					</article>
					<article class="media border-0 content-section-main ">
						<div class="media-body  p-0">
						
							<h4 class="article-title-border pb-2">
								<a href="#" class="article-title ">
									Python Part 4 , Go and grab the opurtunity
								</a>
								<i class="fa float-right text-white fa-bookmark"></i>
							</h4>
							<i class="fa float-right text-white fa-bookmark"></i>
							
						
							<div class="article-metadata border-bottom pb-2">
								<div>
									
									
									<p class="text-muted float-right">  3 June,2020</p>
								</div>
								<p><i class="fa fa-eye"></i> 20 views 
									<i class="fa fa-sign-language"></i> 50 appreciations
								</p>
								<div class="article-tags">
									<a class="tags">Python</a>
									<a class="tags">Django</a>
								    <a class="tags">Html</a>
									<a href="" class="tags">Wow </a>
								</div>
							</div>

							
					

							<div class="article-content text-muted">
								<p>My name is Ajay Kumar and I wnat to kanow how are the things goint gin th ps f </p>
								
							</div>
							<button type="submit" class="btn btn-outline-info">See the full Post</button>
					
						
						</div>
						
					</article>
					
					
			    </div>
			     <div class="p-3 shadow rounded my-4">
					<div class="divider bg-light mt-2 p-2">
						<h2 >Projects</h2>
						<a href="#" class="align-center">see more</a>
					</div>
					<div>
						<h4>My first project</h4>
						<p>Sker is good dont worry</p>
					</div>
					<div>
						<h4>My SEcond project</h4>
						<p>Whats so ever my name is</p>
					</div>
			    </div>
			


			</div>
			<div class="col-md-4 d-sm-none d-md-block hide-small">
				<div class="content-section">
					<h3 class="text-center">Shortcuts</h3>
					
					<ul>
					
						<a href="{% url 'post:Create_Post' %}" class="list-group-item  float-center btn shortcuts dropdown-item text-center">Create Post</a>
						<a href="{% url 'user:createpage' %}" class="list-group-item  float-center btn shortcuts dropdown-item text-center">Create Page</a>
						
					</ul>
				    		
				</div>
			</div>
			
		</div>
    </div>
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
		  	<div class="modal-dialog modal-dialog-centered" role="document">
		  	 	<div class="modal-content">
			      	<div class="modal-header followers-header">
			        	<h5 class="modal-title text-center" id="exampleModalLongTitle">Followers</h5>
			        	<button type="button" class="close" data-dismiss="modal" aria-label="Close">
			          	<span aria-hidden="true">&times;</span>
			        	</button>
			      	</div>
			      	<div class="modal-body followers-body" id="followers-body">
			      		
		      		</div>
							

			      </div>
			</div>
</div>
	



{% endblock %}

   {% block javascript %}
   	<script type="text/javascript">

   		/*
   		$("#follow").submit(function(event){
   			event.preventDefault();
   			alert('clicked');

   			$.ajax({
   				type: 'POST',
   				url :"{% url 'user:follow' pk=profile is_page=profile.content_object.is_page %}",
   				success:function(){
   					console.log('great');
   				};

   			});

   			
   			
   		});
		*/
	$(document).ready(function(){
		$('#follow').on('click',function(event){
			console.log('clicked');
			event.preventDefault();

			$.ajax({
				type : "POST",
				url  :  "{% url 'user:follow' pk=profile.slug is_page=profile.content_object.is_page %}",
   				
				success: function(msg){
					if (msg=='Created'){
						//alert('created ');
						$("#follow .btn").text('Following');
						console.log(this);
					}
					else{
						//alert('deleted');
						$("#follow .btn").text('Follow');
						
					}

				}
   			
			});
			return false;
		});


		$('#follow2').on('click', function(event){
			console.log('clicked');
			event.preventDefault();

			$.ajax({
				type : "POST",
				url  :  "{% url 'user:follows' pk=profile.slug %}",
   				
				success: function(){
					alert('Created New User');

				}
   			
			});
			return false;
		});


		$('#for_followers').on('click',function(event){
			console.log('clicked');
			event.preventDefault();

			$.ajax({
				url  :  "{% url 'user:for_followers' %}",
   				
				success: function(msg){
					console.log(msg)
					$("#followers-body").empty();
					for(i=0; i<msg.length ; i++){
						name=msg[i].name;
						img=msg[i].img;
						slug=msg[i].slug;

						var img_html = '<img src="'+img+'" class="rounded-circle profile-small-image-follower">'
						var name_html = '<span class="search-sort__sort"><a href="/p/'+slug+'/">'+name+'</a></span>'

						$("#followers-body").append('<div>'+img_html+name_html+'</div>')


						
					
					}
					if(msg.length==0){
						$("#followers-body").append('<h4> No followers yet</h4>')

					}
					$("#exampleModalCenter").modal('show');

				}
   			
			});
			return false;
		});




	});


   		// url :"{% url 'user:follow' pk=profile is_page=profile.content_object.is_page %}",
   				
   	</script>


   {% endblock %}

user/templates/user/updateprofile.html
{% extends 'user/base.html' %}
{% load static %}
{% load bootstrap %}
{%  block css %}
	<link rel="stylesheet" href="{% static 'user/profile.css' %}" type="text/css" />

	<style type="text/css">
		#id_members{
		
		}

	</style>

{%  endblock %}
{% block content %}
<span class="nav-below"></span>
<hr/>
<div class="container bg-white">
		<div class="row">
			<div class="col-md-8">
				<form method="Post" enctype="multipart/form-data">
					{% csrf_token %}
					{{ unique_form|bootstrap }}
					{{ profile_form|bootstrap }}
					
					<button class="btn btn-primary">Update Profile</button>

				</form>
				

			</div>
			<div class="col-md-4 d-sm-none d-md-block hide-small">
				<div class="content-section">
					<h3 class="text-center">Shortcuts</h3>
					
					<ul>
						<a href="posts.html" class="list-group-item  float-center btn shortcuts dropdown-item text-center">Go to your Posts</a>
						
						<li class="list-group-item btn shortcuts" >Create Post</li>
						<li class="list-group-item btn shortcuts">Create Project</a></li>
						<li class="list-group-item btn shortcuts">Create Project Banner</li>
						<li class="list-group-item btn shortcuts">First Page </li>
						<li class="list-group-item btn shortcuts">Second Page</li>
					</ul>
				    		
				</div>
			</div>
			
		</div>
    </div>



{% endblock %}