mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

from django.conf.urls.static import static
from django.contrib.auth import views as  auth_views

from django.conf import settings
import user,post,project


urlpatterns = [
    path('admin/', admin.site.urls),
    
    url('ckeditor/', include('ckeditor_uploader.urls')),
    path('tinymce/', include('tinymce.urls')),
  
   
    path('',include('user.urls')),
   	path('',include('post.urls')),
   	path('',include('project.urls')),

     path('password-reset/', 
        auth_views.PasswordResetView.as_view(template_name='templates/password-reset.html'),
         name='password-reset'),
    path('password-reset/done/', 
        auth_views.PasswordResetDoneView.as_view(template_name='templates/password-reset-done.html'),
         name='password-reset-done'),

    path('password-reset-confirm/<uidb64>/<token>',
        auth_views.PasswordResetConfirmView.as_view(template_name='templates/password_reset_confirm.html'),
         name='password_reset_confirm'),
   
   

   
   

]

urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

post/urls.py
''' POST URLS '''

from django.urls import path
from . import views

app_name = 'post'

urlpatterns = [
  
    path('posts/',  views.postlist.as_view() , name="Posts"),
    path('postslist/', views.postlistview, name="postslist"),
    path('posts/<slug:pk>/', views.postdetail, name="Post_Details"),
    path('folders/<slug:pk>/', views.folder, name="Folder"),
    
    path('createpost/', views.createpost.as_view(), name="Create_Post"),
    path('postdetail/<slug:slug>/', views.postdetailview.as_view(), name= "postdetail"),
    path('updatepost/<slug:slug>/', views.updatepostclass.as_view(), name= "updatepost"),
    #path('<slug:ppk>/<slug:pk>/updatepost/', views.updatepost, name="Update_Post"),
    path('<slug:pk>/updatepost/', views.updatepost, name="Update_Post"),
    
    path('<slug:ppk>/<slug:pk>/deletepost/', views.deletepost, name="Delete_Post"),
    
    path('validate-tag/' , views.validatetag, name='validate-tag'),
    path('tag_complete', views.tagcomplete , name='tag_complete'),

    path('tagserach/<pk>/', views.tagserach, name= 'searchtag'),
    path('tagserachs/<pk>/' , views.posttagdetail.as_view(), name='tagserachs'),
]

user/urls.py
from django.urls import path
from django.contrib.auth import views as  auth_views


#from . import views
from . import views 

app_name = 'user'

urlpatterns = [
    path('', views.home),
    path('signup/', views.signup),
    path('sign/',views.sign),
    path('home/' , views.home, name='home'),
    path('p/<slug:pk>/',views.profile, name='profile'),
   	path('p/<slug:pk>/<is_page>/update-profile/',views.updateprofile, name='updateprofile'),
    path('validate-username/', views.validate_username,name='validate-username'),

    path('createpage/', views.createpage.as_view(), name="createpage"),

    path('follow/<pk>/<is_page>/', views.follow, name='follow'),
    path('follows/<pk>/', views.follows, name='follows'),
    path('for_followers/', views.for_followers , name='for_followers'),

    path('ownlogin/', views.ownlogin, name='ownlogin'),
    path('login/', auth_views.LoginView.as_view(template_name='user/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='user/sign.html'), name='logout'),
   
   

    	





   
   


]

templates/base.html
{% load static %}
{% load bootstrap %}
<!DOCTYPE HTML>

<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
  <meta name="viewport" 
  content="width=device-width" initial-scale="1.0"/>

  <title>Funny Learning</title>
  
  <!-- css style sheets and Bootstrap -->
  
  <link rel="stylesheet" type="text/css" 
   href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" />
  
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  
  <script type="text/javascript" charset="utf-8"
    src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
 
   
  <link rel="stylesheet" href="{% static 'user/base.css' %}"
  type="text/css" />
  
  {% block css %}
  {% endblock %}
  
  <!--javascript and j-query -->
  
  
    
  </head>
  <body>
    <nav class="navbar fixed-top navbar-expand-md navbar-light ">
       <a class="navbar-brand text-primary" href="index.html">
          <span class="text-dark">F</span>unny 
          <span class="text-dark">L</span>earning
        </a>

        <button class="navbar-toggler" 
          type="button" data-toggle="collapse" 
          data-target="#navbarNav" >
          
           <span class="navbar-toggler-icon">
           </span>
        </button>
        <div class="collapse navbar-collapse"
            id="navbarNav">
            <div class="navbar-nav text-center">
                <div class="nav-box-grid d-md-none">
                   <a href="login.html" 
                    class="text-center main-link">Log in</a>
                   <a href="signup.html" 
                    class="text-center main-link">Sign in</a>
                </div>
                <form class="nav-form-inline">
                  <input class="form-control" type="search" placeholder="Search">
                 <button class="btn " type="submit">
                   <img src="images/search.png" width="30px" alt="" />
                 </button>
                </form>
                <a class="nav-item nav-link font-weight-bold "
                    href="{% url 'user:home' %}">Home</a>
                <a class="nav-item font-weight-bold  nav-link"
                    href="{% url 'post:Posts' %}">Posts</a>
              
               {% if user.is_authenticated %}      
                <a class="text-primary d-none font-weight-bold d-md-block nav-link" 
                    href="{% url 'user:profile' user.username %}">Profile</a>
                <a class="text-primary d-none font-weight-bold d-md-block nav-link " 
                    href="{% url 'user:logout' %}">Logout</a>   
                {% else %}
                  <a class="text-primary d-none font-weight-bold d-md-block nav-link" 
                    href="{% url 'user:login' %}">Log in</a>
                  <a class="text-primary d-none font-weight-bold d-md-block nav-link " 
                    href="signup.html">Sign in</a>   
                


                {% endif %}


                    
                    
            </div>
        </div>
    </nav>
    <span class="nav-below"></span>
    {% block content %}
    {% endblock %}
    
    
    <footer class="page-footer font-small bg-secondary">
      <div class="footer-copyright text-center py-3">© 2020 Copyright:
        <a href="#" class="text-white">Funnylearning.com</a>
      </div>
    </footer>
    {% block javascript %}
    {% endblock %}
  </body>
</html>

templates/password-reset-done.html
<h1> An email was sent to you </h1>

templates/password-reset.html
{% load static %}
{% load bootstrap %}
<h3>Password reset email</h3>

<form method="POST">
	{% csrf_token %}
	{{ form|bootstrap }}
	<button>Reset Password</button>
</form>

templates/password_reset_confirm.html
{% load static %}
{% load bootstrap %}
<h3> Retype Password</h3>


<form method="POST">
	{% csrf_token %}
	{{ form|bootstrap }}
	<button>Reset Password</button>
</form>